import usePOSTAddOneDepartmentClearanceRequirement from './usePOSTAddOneDepartmentClearanceRequirement';
import useGETDepartmentClearanceRequirementsByDepartmentID from './useGETDepartmentClearanceRequirementsByDepartmentID';

export default {
  usePOSTAddOneDepartmentClearanceRequirement,
  useGETDepartmentClearanceRequirementsByDepartmentID,
};
