import usePOSTAddOneDepartmentClearanceRequirement from './usePOSTAddOneDepartmentClearanceRequirement';
import useGETDepartmentClearanceRequirementsByDepartmentID from './useGETDepartmentClearanceRequirementsByDepartmentID';

export {
  usePOSTAddOneDepartmentClearanceRequirement,
  useGETDepartmentClearanceRequirementsByDepartmentID,
};
